name: Deploy Node App

on:
  push:
    branches: [ dev, main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t yourdockerhub/nodeapp:${{ github.sha }} .
          docker push yourdockerhub/nodeapp:${{ github.sha }}

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull yourdockerhub/nodeapp:${{ github.sha }}
            docker stop nodeapp || true
            docker rm nodeapp || true
            docker run -d -p 80:3000 --name nodeapp yourdockerhub/nodeapp:${{ github.sha }}
